### ISSUE TITLE
no support botania mod~~

### ISSUE THREAD

**Issue by PorPit** [jaredlll08/CraftTweaker#250]
Script: mods.botania.ElvenTrade.addRecipe([<minecraft:yellow_flower>], [<minecraft:yellow_flower>]);

log：
[SERVER_STARTED][SERVER][ERROR] edited_recipes.zs:1 > No such member: botania
[SERVER_STARTED][SERVER][ERROR] Error executing edited_recipes.zs: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:168)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:24)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:175)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:79)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:37)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:20)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:113)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:149)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:508)
	at minetweaker.MineTweakerImplementationAPI.lambda$static$0(MineTweakerImplementationAPI.java:70)
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:493)
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:110)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by jaredlll08** [comment]
Wrong repo.
Follow the issue template.
Install Modtweaker.
