### ISSUE TITLE
Hiding Items in JEI 1.10.2 

### ISSUE THREAD

**Issue by s-grimm** [jaredlll08/CraftTweaker#39]
Version: 3.0.10
Script File [jei.zs.txt](https://github.com/jaredlll08/CraftTweaker/files/387454/jei.zs.txt)
Log: [minetweaker.log.txt](https://github.com/jaredlll08/CraftTweaker/files/387456/minetweaker.log.txt)

Unable to hide items in JEI. /mt reload does not display errors in the script.

**Comment by jaredlll08** [comment]
Fix the other errors in your script, it says something about botania, fix that, then retry

**Comment by s-grimm** [comment]
The Botania errors are in their own script file, so they shouldn't be causing any issues with the jei script. I'll upload a copy of the log with just the JEI scripts running if you think that the issue is being caused by having multiple scripts running.

**Comment by jaredlll08** [comment]
Scripts get weird if there is an error before. It may actually solve the
issue, and you need to fix that botania issue anyway.

**Comment by s-grimm** [comment]
Here's the log when just running the jei.zs script I linked above: 
[minetweaker.log.txt](https://github.com/jaredlll08/CraftTweaker/files/389362/minetweaker.log.txt)

**Comment by Carrots4U** [comment]
I can't hide any items either, getting the same error.

**Comment by Nentify** [comment]
Same thing, another example:

```
ERROR: Error executing tekkify.zs: null
java.lang.NullPointerException
	at minetweaker.mods.jei.JEI$JEIHideItemAction.apply(JEI.java:47)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:176)
	at minetweaker.mods.jei.JEI.hide(JEI.java:35)
	at Tekkify.__script__(tekkify.zs:150)
	at __ZenMain__.run(tekkify.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:161)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:591)
	at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:838)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by jaredlll08** [comment]
try updating JEI

**Comment by Nentify** [comment]
I am on the latest version (3.7.8.234)

**Comment by s-grimm** [comment]
I am also on the latest version (3.7.8.234)

**Comment by utoc** [comment]
Chiming in with this error as well.

I get the aforementioned NPE upon client startup when using `mods.jei.JEI.hide` however, if I `/mt reload` I do not get an NPE, however, the item isn't hidden either.  The log chirps that the item is being hidden but does not actually do it.

I am running:

jei_1.10.2-3.7.8.234
CraftTweaker-1.10.2-3.0.10
ModTweaker2-2.0.0
forge-1.10.2-12.18.1.2044 (but have also tried with 2011, 2042)
on MC 1.10.2

**Comment by Carrots4U** [comment]
I also have the same issue as @utoc, so it's reproducible.

**Comment by elwooha6** [comment]
Having same issue, loading config in Singleplayer gives the error, reloading the config ingame gives no error but still doesn't hide anything from JEI.

Log is here:
http://pastebin.com/7NTSXkDd
